### ISSUE TITLE
Dialog should communicate scenario details

### ISSUE THREAD

**Issue by Poobslag** [Poobslag/turbofat#153]
#90 describes how the overworld icon should have an icon, but this should also appear when you talk to the customer.

They could say something generic like, "I was hoping you could help me in my kitchen today!" and a popup window could appear with some details:

```
  Goal: 100 points
  Bonus: Finish as fast as you can!
  Difficulty: Medium hard
  Reward: $2000
  Other: Your next pieces are untrustworthy
```

Or maybe something more thematic:

```
  Order: 1,000 kCal of food, as fast as possible!
  Urgency: I'll get to it frosting tomorrow morning...
  Bill: $20.00
  Other: 
```
